using DatesErp.Application.Services;
using DatesErp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Xunit;

namespace DatesErp.Tests;

/// <summary>
/// §B52 — نوافذ المجموعات/الوحدات/الأصناف المترابطة وقواعد الحماية:
///  • المجموعة تُضاف **بلا حقل وحدة** ولا تُفرض عليها وحدة افتراضية، وكودها يُولَّد تلقائياً.
///  • منع تكرار اسم المجموعة والوحدة؛ والتعطيل بدل الحذف.
///  • الوحدة تُقرأ من قاموس الوحدات وتُحفظ على الصنف كما اختيرت.
///  • أي مجموعة/وحدة جديدة تنعكس في الشاشات المرتبطة (الاستلام/التخطيط/…) لأنها تقرأ من قاعدة البيانات.
/// </summary>
public class MasterDataB52Tests
{
    private static MasterDataService Svc(TestHost host)
        => (MasterDataService)host.Services.CreateScope().ServiceProvider.GetService(typeof(MasterDataService));

    private static DatesErpDbContext Db(TestHost host)
        => new DatesErpDbContext(new DbContextOptionsBuilder<DatesErpDbContext>().UseSqlite(host.Connection).Options);

    [Fact]
    public void Group_Added_Without_Unit_And_Code_AutoGenerated()
    {
        using var host = new TestHost();
        host.LoginAsAdmin();

        var r = Svc(host).SaveItemGroup(null, "", "مواد تعبئة وتغليف", "Pack", null);
        Assert.True(r.Ok, r.Message);

        using var db = Db(host);
        var g = db.ItemGroups.Single(x => x.GroupNameAr == "مواد تعبئة وتغليف");
        Assert.Equal("005", g.GroupCode);            // التالي تلقائياً بعد 004
        Assert.True(string.IsNullOrEmpty(g.DefaultUnit), "المجموعة لا تحمل وحدة — الوحدات للأصناف.");
        Assert.True(g.IsActive);
    }

    [Fact]
    public void Group_Duplicate_Name_Is_Rejected()
    {
        using var host = new TestHost();
        host.LoginAsAdmin();

        Assert.True(Svc(host).SaveItemGroup(null, "009", "مجموعة تجريبية", "Raw", null).Ok);
        var dup = Svc(host).SaveItemGroup(null, "010", "مجموعة تجريبية", "Raw", null);
        Assert.False(dup.Ok);
        Assert.Contains("بنفس الاسم", dup.Message);
    }

    [Fact]
    public void Group_Toggle_Disables_Without_Deleting_Products()
    {
        using var host = new TestHost();
        host.LoginAsAdmin();

        using (var db = Db(host))
        {
            var g = db.ItemGroups.Single(x => x.GroupCode == "001");
            Assert.True(db.Products.Any(p => p.GroupCode == "001"));  // مجموعة مستخدمة
            var r = Svc(host).ToggleItemGroup(g.Id);
            Assert.True(r.Ok, r.Message);
        }
        using var db2 = Db(host);
        Assert.False(db2.ItemGroups.Single(x => x.GroupCode == "001").IsActive);
        Assert.True(db2.Products.Any(p => p.GroupCode == "001"));    // الأصناف لا تُحذف
    }

    [Fact]
    public void Unit_Duplicate_Name_Is_Rejected()
    {
        using var host = new TestHost();
        host.LoginAsAdmin();

        var dup = Svc(host).SaveUnit(null, "كجم");   // موجودة في البذر
        Assert.False(dup.Ok);
        Assert.Contains("بنفس الاسم", dup.Message);
    }

    [Fact]
    public void Unit_New_Is_Stored_And_Available_For_Items()
    {
        using var host = new TestHost();
        host.LoginAsAdmin();

        var r = Svc(host).SaveUnit(null, "كيس");
        Assert.True(r.Ok, r.Message);

        // الصنف يحفظ الوحدة المختارة من القاموس كما هي
        var p = Svc(host).SaveProductFull(null, "001-500", "سكر خام معبأ أكياس", "001", "Raw", "كيس", 0, 0, 0, null);
        Assert.True(p.Ok, p.Message);

        using var db = Db(host);
        var item = db.Products.Single(x => x.ProductCode == "001-500");
        Assert.Equal("كيس", item.UnitOfMeasure);
        // وشاشة الاستلام تقرأ أصناف الخام من قاعدة البيانات — الصنف الجديد ظاهر لها
        Assert.Contains(db.Products.AsNoTracking().Where(x => x.ItemType == "Raw" && x.IsActive).ToList(),
            x => x.Id == item.Id);
    }

    [Fact]
    public void Item_In_Custom_Active_Group_Keeps_That_Group()
    {
        using var host = new TestHost();
        host.LoginAsAdmin();

        Assert.True(Svc(host).SaveItemGroup(null, "", "تمور فاخرة للتصدير", "Raw", null).Ok);
        var r = Svc(host).SaveProductFull(null, "005-001", "خلاص تصدير فاخر", "005", "Raw", "كجم", 0, 0, 0, null);
        Assert.True(r.Ok, r.Message);

        using var db = Db(host);
        var item = db.Products.Single(x => x.ProductCode == "005-001");
        Assert.Equal("005", item.GroupCode);     // المجموعة المختارة هي المحفوظة
        Assert.Equal("Raw", item.ItemType);      // والنوع ما زال خاماً فتتعامل معه الشاشات
    }

    [Fact]
    public void Finished_Item_With_Carton_Unit_Flows_To_Finished_Screens()
    {
        using var host = new TestHost();
        host.LoginAsAdmin();

        var r = Svc(host).SaveProductFull(null, "002-900", "تمر سليم عبوة خاصة", "002", "Finished", "كرتون",
            10, 5, 2, new System.Collections.Generic.List<(int, int?, int)>());
        Assert.True(r.Ok, r.Message);

        using var db = Db(host);
        var item = db.Products.Single(x => x.ProductCode == "002-900");
        Assert.Equal("كرتون", item.UnitOfMeasure);
        Assert.Equal(10, item.CartonWeightKg);          // 5 قوالب × 2 كجم
        Assert.Equal("Finished", item.ItemType);
        // التخطيط يقرأ المنتجات التامة من قاعدة البيانات — الصنف ظاهر له
        Assert.Contains(db.Products.AsNoTracking().Where(x => x.ItemType == "Finished" && x.IsActive).ToList(),
            x => x.Id == item.Id);
    }

    [Fact]
    public void Used_Unit_Cannot_Be_Removed_Only_Disabled()
    {
        using var host = new TestHost();
        host.LoginAsAdmin();

        using (var db = Db(host))
        {
            var u = db.UnitsOfMeasure.Single(x => x.UnitNameAr == "كجم");   // مستخدمة في أصناف
            var r = Svc(host).ToggleUnit(u.Id);
            Assert.True(r.Ok, r.Message);
        }
        using var db2 = Db(host);
        Assert.False(db2.UnitsOfMeasure.Single(x => x.UnitNameAr == "كجم").IsActive);
        // الأصناف التي تستخدمها تبقى كما هي
        Assert.True(db2.Products.Any(p => p.UnitOfMeasure == "كجم"));
    }
}
